# Generated by Django 2.2.5 on 2021-07-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='chash on dilevry', max_length=20),
        ),
    ]
